name: Gradle-CI
#Triggers: On push and PR:
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
#Jobs: Mention all jobs to run.
jobs:
#build: Name of the job. E.g, build, build_and_test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build
      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: build/reports/tests/test
